/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gr.grnet.aquarium.message.avro;  
@SuppressWarnings("all")
public class _EffectivePriceTable extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"_EffectivePriceTable\",\"namespace\":\"gr.grnet.aquarium.message.avro\",\"fields\":[]}");
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /** Creates a new _EffectivePriceTable RecordBuilder */
  public static gr.grnet.aquarium.message.avro._EffectivePriceTable.Builder newBuilder() {
    return new gr.grnet.aquarium.message.avro._EffectivePriceTable.Builder();
  }
  
  /** Creates a new _EffectivePriceTable RecordBuilder by copying an existing Builder */
  public static gr.grnet.aquarium.message.avro._EffectivePriceTable.Builder newBuilder(gr.grnet.aquarium.message.avro._EffectivePriceTable.Builder other) {
    return new gr.grnet.aquarium.message.avro._EffectivePriceTable.Builder(other);
  }
  
  /** Creates a new _EffectivePriceTable RecordBuilder by copying an existing _EffectivePriceTable instance */
  public static gr.grnet.aquarium.message.avro._EffectivePriceTable.Builder newBuilder(gr.grnet.aquarium.message.avro._EffectivePriceTable other) {
    return new gr.grnet.aquarium.message.avro._EffectivePriceTable.Builder(other);
  }
  
  /**
   * RecordBuilder for _EffectivePriceTable instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<_EffectivePriceTable>
    implements org.apache.avro.data.RecordBuilder<_EffectivePriceTable> {


    /** Creates a new Builder */
    private Builder() {
      super(gr.grnet.aquarium.message.avro._EffectivePriceTable.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(gr.grnet.aquarium.message.avro._EffectivePriceTable.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing _EffectivePriceTable instance */
    private Builder(gr.grnet.aquarium.message.avro._EffectivePriceTable other) {
            super(gr.grnet.aquarium.message.avro._EffectivePriceTable.SCHEMA$);
    }

    @Override
    public _EffectivePriceTable build() {
      try {
        _EffectivePriceTable record = new _EffectivePriceTable();
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
