/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gr.grnet.aquarium.message.avro;  
@SuppressWarnings("all")
public enum _EventVersion { 
  VERSION_1_0  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"_EventVersion\",\"namespace\":\"gr.grnet.aquarium.message.avro\",\"symbols\":[\"VERSION_1_0\"]}");
}
