/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gr.grnet.aquarium.message.avro;  
@SuppressWarnings("all")
public class _FullPriceTable extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"_FullPriceTable\",\"namespace\":\"gr.grnet.aquarium.message.avro\",\"fields\":[{\"name\":\"perResource\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"_SelectorValue\",\"fields\":[{\"name\":\"selectorValue\",\"type\":[{\"type\":\"record\",\"name\":\"_EffectivePriceTable\",\"fields\":[]},{\"type\":\"map\",\"values\":\"_SelectorValue\"}]}]}}}}]}");
  @Deprecated public java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._SelectorValue>> perResource;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return perResource;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: perResource = (java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._SelectorValue>>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'perResource' field.
   */
  public java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._SelectorValue>> getPerResource() {
    return perResource;
  }

  /**
   * Sets the value of the 'perResource' field.
   * @param value the value to set.
   */
  public void setPerResource(java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._SelectorValue>> value) {
    this.perResource = value;
  }

  /** Creates a new _FullPriceTable RecordBuilder */
  public static gr.grnet.aquarium.message.avro._FullPriceTable.Builder newBuilder() {
    return new gr.grnet.aquarium.message.avro._FullPriceTable.Builder();
  }
  
  /** Creates a new _FullPriceTable RecordBuilder by copying an existing Builder */
  public static gr.grnet.aquarium.message.avro._FullPriceTable.Builder newBuilder(gr.grnet.aquarium.message.avro._FullPriceTable.Builder other) {
    return new gr.grnet.aquarium.message.avro._FullPriceTable.Builder(other);
  }
  
  /** Creates a new _FullPriceTable RecordBuilder by copying an existing _FullPriceTable instance */
  public static gr.grnet.aquarium.message.avro._FullPriceTable.Builder newBuilder(gr.grnet.aquarium.message.avro._FullPriceTable other) {
    return new gr.grnet.aquarium.message.avro._FullPriceTable.Builder(other);
  }
  
  /**
   * RecordBuilder for _FullPriceTable instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<_FullPriceTable>
    implements org.apache.avro.data.RecordBuilder<_FullPriceTable> {

    private java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._SelectorValue>> perResource;

    /** Creates a new Builder */
    private Builder() {
      super(gr.grnet.aquarium.message.avro._FullPriceTable.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(gr.grnet.aquarium.message.avro._FullPriceTable.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing _FullPriceTable instance */
    private Builder(gr.grnet.aquarium.message.avro._FullPriceTable other) {
            super(gr.grnet.aquarium.message.avro._FullPriceTable.SCHEMA$);
      if (isValidValue(fields()[0], other.perResource)) {
        this.perResource = (java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._SelectorValue>>) data().deepCopy(fields()[0].schema(), other.perResource);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'perResource' field */
    public java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._SelectorValue>> getPerResource() {
      return perResource;
    }
    
    /** Sets the value of the 'perResource' field */
    public gr.grnet.aquarium.message.avro._FullPriceTable.Builder setPerResource(java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._SelectorValue>> value) {
      validate(fields()[0], value);
      this.perResource = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'perResource' field has been set */
    public boolean hasPerResource() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'perResource' field */
    public gr.grnet.aquarium.message.avro._FullPriceTable.Builder clearPerResource() {
      perResource = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public _FullPriceTable build() {
      try {
        _FullPriceTable record = new _FullPriceTable();
        record.perResource = fieldSetFlags()[0] ? this.perResource : (java.util.Map<java.lang.CharSequence,java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._SelectorValue>>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
