/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gr.grnet.aquarium.message.avro;  
@SuppressWarnings("all")
public class _Policy extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"_Policy\",\"namespace\":\"gr.grnet.aquarium.message.avro\",\"fields\":[{\"name\":\"ID\",\"type\":\"string\",\"aliases\":[\"id, _id, idInStore, inStoreID\"]},{\"name\":\"parentID\",\"type\":\"string\"},{\"name\":\"validFromMillis\",\"type\":\"long\"},{\"name\":\"validToMillis\",\"type\":\"long\"},{\"name\":\"resourceTypes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"_ResourceType\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"unit\",\"type\":\"string\"},{\"name\":\"chargingBehaviorClass\",\"type\":\"string\"}]}}},{\"name\":\"chargingBehaviors\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"roleMapping\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"_FullPriceTable\",\"fields\":[{\"name\":\"perResource\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"_SelectorValue\",\"fields\":[{\"name\":\"selectorValue\",\"type\":[{\"type\":\"record\",\"name\":\"_EffectivePriceTable\",\"fields\":[]},{\"type\":\"map\",\"values\":\"_SelectorValue\"}]}]}}}}]}}}]}");
  @Deprecated public java.lang.CharSequence ID;
  @Deprecated public java.lang.CharSequence parentID;
  @Deprecated public long validFromMillis;
  @Deprecated public long validToMillis;
  @Deprecated public java.util.List<gr.grnet.aquarium.message.avro._ResourceType> resourceTypes;
  @Deprecated public java.util.List<java.lang.CharSequence> chargingBehaviors;
  @Deprecated public java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._FullPriceTable> roleMapping;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ID;
    case 1: return parentID;
    case 2: return validFromMillis;
    case 3: return validToMillis;
    case 4: return resourceTypes;
    case 5: return chargingBehaviors;
    case 6: return roleMapping;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ID = (java.lang.CharSequence)value$; break;
    case 1: parentID = (java.lang.CharSequence)value$; break;
    case 2: validFromMillis = (java.lang.Long)value$; break;
    case 3: validToMillis = (java.lang.Long)value$; break;
    case 4: resourceTypes = (java.util.List<gr.grnet.aquarium.message.avro._ResourceType>)value$; break;
    case 5: chargingBehaviors = (java.util.List<java.lang.CharSequence>)value$; break;
    case 6: roleMapping = (java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._FullPriceTable>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ID' field.
   */
  public java.lang.CharSequence getID() {
    return ID;
  }

  /**
   * Sets the value of the 'ID' field.
   * @param value the value to set.
   */
  public void setID(java.lang.CharSequence value) {
    this.ID = value;
  }

  /**
   * Gets the value of the 'parentID' field.
   */
  public java.lang.CharSequence getParentID() {
    return parentID;
  }

  /**
   * Sets the value of the 'parentID' field.
   * @param value the value to set.
   */
  public void setParentID(java.lang.CharSequence value) {
    this.parentID = value;
  }

  /**
   * Gets the value of the 'validFromMillis' field.
   */
  public java.lang.Long getValidFromMillis() {
    return validFromMillis;
  }

  /**
   * Sets the value of the 'validFromMillis' field.
   * @param value the value to set.
   */
  public void setValidFromMillis(java.lang.Long value) {
    this.validFromMillis = value;
  }

  /**
   * Gets the value of the 'validToMillis' field.
   */
  public java.lang.Long getValidToMillis() {
    return validToMillis;
  }

  /**
   * Sets the value of the 'validToMillis' field.
   * @param value the value to set.
   */
  public void setValidToMillis(java.lang.Long value) {
    this.validToMillis = value;
  }

  /**
   * Gets the value of the 'resourceTypes' field.
   */
  public java.util.List<gr.grnet.aquarium.message.avro._ResourceType> getResourceTypes() {
    return resourceTypes;
  }

  /**
   * Sets the value of the 'resourceTypes' field.
   * @param value the value to set.
   */
  public void setResourceTypes(java.util.List<gr.grnet.aquarium.message.avro._ResourceType> value) {
    this.resourceTypes = value;
  }

  /**
   * Gets the value of the 'chargingBehaviors' field.
   */
  public java.util.List<java.lang.CharSequence> getChargingBehaviors() {
    return chargingBehaviors;
  }

  /**
   * Sets the value of the 'chargingBehaviors' field.
   * @param value the value to set.
   */
  public void setChargingBehaviors(java.util.List<java.lang.CharSequence> value) {
    this.chargingBehaviors = value;
  }

  /**
   * Gets the value of the 'roleMapping' field.
   */
  public java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._FullPriceTable> getRoleMapping() {
    return roleMapping;
  }

  /**
   * Sets the value of the 'roleMapping' field.
   * @param value the value to set.
   */
  public void setRoleMapping(java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._FullPriceTable> value) {
    this.roleMapping = value;
  }

  /** Creates a new _Policy RecordBuilder */
  public static gr.grnet.aquarium.message.avro._Policy.Builder newBuilder() {
    return new gr.grnet.aquarium.message.avro._Policy.Builder();
  }
  
  /** Creates a new _Policy RecordBuilder by copying an existing Builder */
  public static gr.grnet.aquarium.message.avro._Policy.Builder newBuilder(gr.grnet.aquarium.message.avro._Policy.Builder other) {
    return new gr.grnet.aquarium.message.avro._Policy.Builder(other);
  }
  
  /** Creates a new _Policy RecordBuilder by copying an existing _Policy instance */
  public static gr.grnet.aquarium.message.avro._Policy.Builder newBuilder(gr.grnet.aquarium.message.avro._Policy other) {
    return new gr.grnet.aquarium.message.avro._Policy.Builder(other);
  }
  
  /**
   * RecordBuilder for _Policy instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<_Policy>
    implements org.apache.avro.data.RecordBuilder<_Policy> {

    private java.lang.CharSequence ID;
    private java.lang.CharSequence parentID;
    private long validFromMillis;
    private long validToMillis;
    private java.util.List<gr.grnet.aquarium.message.avro._ResourceType> resourceTypes;
    private java.util.List<java.lang.CharSequence> chargingBehaviors;
    private java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._FullPriceTable> roleMapping;

    /** Creates a new Builder */
    private Builder() {
      super(gr.grnet.aquarium.message.avro._Policy.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(gr.grnet.aquarium.message.avro._Policy.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing _Policy instance */
    private Builder(gr.grnet.aquarium.message.avro._Policy other) {
            super(gr.grnet.aquarium.message.avro._Policy.SCHEMA$);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = (java.lang.CharSequence) data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.parentID)) {
        this.parentID = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.parentID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.validFromMillis)) {
        this.validFromMillis = (java.lang.Long) data().deepCopy(fields()[2].schema(), other.validFromMillis);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.validToMillis)) {
        this.validToMillis = (java.lang.Long) data().deepCopy(fields()[3].schema(), other.validToMillis);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.resourceTypes)) {
        this.resourceTypes = (java.util.List<gr.grnet.aquarium.message.avro._ResourceType>) data().deepCopy(fields()[4].schema(), other.resourceTypes);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.chargingBehaviors)) {
        this.chargingBehaviors = (java.util.List<java.lang.CharSequence>) data().deepCopy(fields()[5].schema(), other.chargingBehaviors);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.roleMapping)) {
        this.roleMapping = (java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._FullPriceTable>) data().deepCopy(fields()[6].schema(), other.roleMapping);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'ID' field */
    public java.lang.CharSequence getID() {
      return ID;
    }
    
    /** Sets the value of the 'ID' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder setID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'ID' field has been set */
    public boolean hasID() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'ID' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder clearID() {
      ID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'parentID' field */
    public java.lang.CharSequence getParentID() {
      return parentID;
    }
    
    /** Sets the value of the 'parentID' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder setParentID(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.parentID = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'parentID' field has been set */
    public boolean hasParentID() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'parentID' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder clearParentID() {
      parentID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'validFromMillis' field */
    public java.lang.Long getValidFromMillis() {
      return validFromMillis;
    }
    
    /** Sets the value of the 'validFromMillis' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder setValidFromMillis(long value) {
      validate(fields()[2], value);
      this.validFromMillis = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'validFromMillis' field has been set */
    public boolean hasValidFromMillis() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'validFromMillis' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder clearValidFromMillis() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'validToMillis' field */
    public java.lang.Long getValidToMillis() {
      return validToMillis;
    }
    
    /** Sets the value of the 'validToMillis' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder setValidToMillis(long value) {
      validate(fields()[3], value);
      this.validToMillis = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'validToMillis' field has been set */
    public boolean hasValidToMillis() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'validToMillis' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder clearValidToMillis() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'resourceTypes' field */
    public java.util.List<gr.grnet.aquarium.message.avro._ResourceType> getResourceTypes() {
      return resourceTypes;
    }
    
    /** Sets the value of the 'resourceTypes' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder setResourceTypes(java.util.List<gr.grnet.aquarium.message.avro._ResourceType> value) {
      validate(fields()[4], value);
      this.resourceTypes = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'resourceTypes' field has been set */
    public boolean hasResourceTypes() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'resourceTypes' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder clearResourceTypes() {
      resourceTypes = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'chargingBehaviors' field */
    public java.util.List<java.lang.CharSequence> getChargingBehaviors() {
      return chargingBehaviors;
    }
    
    /** Sets the value of the 'chargingBehaviors' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder setChargingBehaviors(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[5], value);
      this.chargingBehaviors = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'chargingBehaviors' field has been set */
    public boolean hasChargingBehaviors() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'chargingBehaviors' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder clearChargingBehaviors() {
      chargingBehaviors = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'roleMapping' field */
    public java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._FullPriceTable> getRoleMapping() {
      return roleMapping;
    }
    
    /** Sets the value of the 'roleMapping' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder setRoleMapping(java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._FullPriceTable> value) {
      validate(fields()[6], value);
      this.roleMapping = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'roleMapping' field has been set */
    public boolean hasRoleMapping() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'roleMapping' field */
    public gr.grnet.aquarium.message.avro._Policy.Builder clearRoleMapping() {
      roleMapping = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public _Policy build() {
      try {
        _Policy record = new _Policy();
        record.ID = fieldSetFlags()[0] ? this.ID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.parentID = fieldSetFlags()[1] ? this.parentID : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.validFromMillis = fieldSetFlags()[2] ? this.validFromMillis : (java.lang.Long) defaultValue(fields()[2]);
        record.validToMillis = fieldSetFlags()[3] ? this.validToMillis : (java.lang.Long) defaultValue(fields()[3]);
        record.resourceTypes = fieldSetFlags()[4] ? this.resourceTypes : (java.util.List<gr.grnet.aquarium.message.avro._ResourceType>) defaultValue(fields()[4]);
        record.chargingBehaviors = fieldSetFlags()[5] ? this.chargingBehaviors : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[5]);
        record.roleMapping = fieldSetFlags()[6] ? this.roleMapping : (java.util.Map<java.lang.CharSequence,gr.grnet.aquarium.message.avro._FullPriceTable>) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
