/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gr.grnet.aquarium.message.avro;  
@SuppressWarnings("all")
public class _SelectorValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"_SelectorValue\",\"namespace\":\"gr.grnet.aquarium.message.avro\",\"fields\":[{\"name\":\"selectorValue\",\"type\":[{\"type\":\"record\",\"name\":\"_EffectivePriceTable\",\"fields\":[]},{\"type\":\"map\",\"values\":\"_SelectorValue\"}]}]}");
  @Deprecated public java.lang.Object selectorValue;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return selectorValue;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: selectorValue = (java.lang.Object)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'selectorValue' field.
   */
  public java.lang.Object getSelectorValue() {
    return selectorValue;
  }

  /**
   * Sets the value of the 'selectorValue' field.
   * @param value the value to set.
   */
  public void setSelectorValue(java.lang.Object value) {
    this.selectorValue = value;
  }

  /** Creates a new _SelectorValue RecordBuilder */
  public static gr.grnet.aquarium.message.avro._SelectorValue.Builder newBuilder() {
    return new gr.grnet.aquarium.message.avro._SelectorValue.Builder();
  }
  
  /** Creates a new _SelectorValue RecordBuilder by copying an existing Builder */
  public static gr.grnet.aquarium.message.avro._SelectorValue.Builder newBuilder(gr.grnet.aquarium.message.avro._SelectorValue.Builder other) {
    return new gr.grnet.aquarium.message.avro._SelectorValue.Builder(other);
  }
  
  /** Creates a new _SelectorValue RecordBuilder by copying an existing _SelectorValue instance */
  public static gr.grnet.aquarium.message.avro._SelectorValue.Builder newBuilder(gr.grnet.aquarium.message.avro._SelectorValue other) {
    return new gr.grnet.aquarium.message.avro._SelectorValue.Builder(other);
  }
  
  /**
   * RecordBuilder for _SelectorValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<_SelectorValue>
    implements org.apache.avro.data.RecordBuilder<_SelectorValue> {

    private java.lang.Object selectorValue;

    /** Creates a new Builder */
    private Builder() {
      super(gr.grnet.aquarium.message.avro._SelectorValue.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(gr.grnet.aquarium.message.avro._SelectorValue.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing _SelectorValue instance */
    private Builder(gr.grnet.aquarium.message.avro._SelectorValue other) {
            super(gr.grnet.aquarium.message.avro._SelectorValue.SCHEMA$);
      if (isValidValue(fields()[0], other.selectorValue)) {
        this.selectorValue = (java.lang.Object) data().deepCopy(fields()[0].schema(), other.selectorValue);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'selectorValue' field */
    public java.lang.Object getSelectorValue() {
      return selectorValue;
    }
    
    /** Sets the value of the 'selectorValue' field */
    public gr.grnet.aquarium.message.avro._SelectorValue.Builder setSelectorValue(java.lang.Object value) {
      validate(fields()[0], value);
      this.selectorValue = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'selectorValue' field has been set */
    public boolean hasSelectorValue() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'selectorValue' field */
    public gr.grnet.aquarium.message.avro._SelectorValue.Builder clearSelectorValue() {
      selectorValue = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public _SelectorValue build() {
      try {
        _SelectorValue record = new _SelectorValue();
        record.selectorValue = fieldSetFlags()[0] ? this.selectorValue : (java.lang.Object) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
